MAX_LENGTH_TAG_NAME = 32
MAX_LENGTH_TAG_SLUG = 32
MAX_LENGTH_INGREDIENT_NAME = 128
MAX_LENGTH_MEASUREMENT_UNIT = 64
MAX_LENGTH_RECIPE_NAME = 256
MAX_LENGTH_SHORT_CODE = 10
MAX_LENGTH_EMAIL = 254
MAX_LENGTH_USERNAME = 150
MAX_LENGTH_FIRST_LAST_NAME = 150

MIN_COOKING_TIME = 1
MIN_AMOUNT = 1
MIN_INGREDIENT_AMOUNT = 1
